#!/usr/bin/env python3
"""Generate Karnak exam question bank JS files from structured question data."""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
EXAM_DIR = os.path.join(ROOT, "api", "exam")

SANITIZE_HEADER = r'''
function sanitizeText(s) {
  if (typeof s !== "string") return s;
  const map = {
    "\u00e2\u20ac\u2122": "\u2019",
    "\u00e2\u20ac\u0153": "\u201c",
    "\u00e2\u20ac\u009d": "\u201d",
    "\u00e2\u20ac\u201c": "\u2013",
    "\u00e2\u20ac\u201d": "\u2014",
    "\u00e2\u20ac\u00a6": "\u2026",
    "\u00c2\u00bd": "\u00bd",
    "\u00c2\u00bc": "\u00bc",
    "\u00c2\u00be": "\u00be",
    "\u00c2\u00b0": "\u00b0",
    "\u00c2\u00ae": "\u00ae",
    "\u00c2\u00a9": "\u00a9",
    "\u00c2\u00b1": "\u00b1",
    "\u00c2\u00b7": "\u00b7",
    "\u00c3\u2014": "\u00d7",
    "\u00c3\u00a9": "\u00e9",
    "\u00c3\u00a8": "\u00e8",
    "\u00c3\u00aa": "\u00ea",
    "\u00c3\u00a1": "\u00e1",
    "\u00c3\u00b3": "\u00f3",
    "\u00c3\u00ba": "\u00fa",
    "\u00c3\u00b1": "\u00f1",
    "\u00c2\u00a0": " ",
    "\u00e2\u20ac": "\u201d"
  };
  let out = s;
  for (const [bad, good] of Object.entries(map)) out = out.split(bad).join(good);
  return out;
}

function sanitizeOption(o) {
  if (!o || typeof o !== "object") return o;
  return { ...o, text: typeof o.text === "string" ? sanitizeText(o.text) : o.text };
}

function sanitizeQuestion(q) {
  if (!q || typeof q !== "object") return q;
  const out = { ...q };
  for (const f of ["question", "explanation", "cite"]) {
    if (typeof out[f] === "string") out[f] = sanitizeText(out[f]);
  }
  if (Array.isArray(out.options)) out.options = out.options.map(sanitizeOption);
  return out;
}
'''

def q(id_, question, options, answer, explanation, cite):
    return {
        "id": id_,
        "type": "mcq",
        "question": question,
        "options": [{"id": k, "text": v} for k, v in options],
        "answer": answer,
        "explanation": explanation,
        "cite": cite,
        "exhibitImage": "",
        "imageRef": "",
    }

K501_CITE = "501-elasto-brite-pds.pdf"
K670_CITE = "670hs-karna-sil-ultra-pds.pdf"
K97_CITE = "97-fibered-aluminum-pds.pdf"

K501 = [
    q("K501-001",
       "A property manager wants Karnak 501 Elasto-Brite applied over a newly installed four-ply built-up roof that was completed 45 days ago. What does the data sheet require before coating can proceed?",
       [("A", "Coating may begin once the roof has dried for 48 hours after the final flood coat"),
        ("B", "The BUR surface must age a minimum of 90 days before 501 Elasto-Brite application"),
        ("C", "Only 30 days of weathering is required for all asphalt-based membranes"),
        ("D", "New BUR may be coated immediately if a Karnak 400-series base coat is used first")],
       "B",
       "New BUR roof surfaces must age a minimum of 90 days before coating. Modified bitumen membranes require 30 days, but BUR has a longer aging requirement.",
       f"{K501_CITE} - Page 1"),
    q("K501-002",
       "A foreman schedules 501 Elasto-Brite over a torched SBS modified bitumen membrane installed 20 days ago. According to Karnak surface preparation requirements, what is the problem?",
       [("A", "SBS membranes never qualify for acrylic elastomeric coatings"),
        ("B", "Newly installed cold-process, hot-applied, and torched-applied modified bitumen membranes should age 30 days before coating"),
        ("C", "Torched membranes require 90 days regardless of reinforcement type"),
        ("D", "Modified bitumen must be torn off before any Karnak acrylic may be applied")],
       "B",
       "Newly installed cold-process, hot-applied, and torched-applied modified bitumen membranes should age 30 days before coating. At 20 days the membrane has not met the minimum weathering period.",
       f"{K501_CITE} - Page 1"),
    q("K501-003",
       "An estimator is pricing restoration over a five-year-old TPO single-ply roof in sound condition. Is 501 Elasto-Brite within the manufacturer's stated approved substrates?",
       [("A", "No; TPO requires silicone only and cannot accept acrylic coatings"),
        ("B", "Yes; aged TPO and PVC (minimum four years old) are listed approved substrates"),
        ("C", "Only if the TPO is less than two years old and still factory-white"),
        ("D", "TPO is approved only when coated over 180 Karna-Sil Ultra Epoxy Primer")],
       "B",
       "501 Elasto-Brite is designed for aged TPO and PVC that are a minimum of four years old, along with aged BUR, modified bitumen, and metal roofs.",
       f"{K501_CITE} - Page 1"),
    q("K501-004",
       "During a pre-job walk, the crew finds wet insulation under a blistered BUR field area. Before 501 Elasto-Brite work begins, what does Karnak require?",
       [("A", "Seal the blister with mastic and coat over the wet area the same day"),
        ("B", "All wet insulation should be removed and replaced with like materials"),
        ("C", "Power wash only; wet insulation may remain if the surface dries in 24 hours"),
        ("D", "Apply 501 Elasto-Brite in a heavy flood coat to encapsulate the moisture")],
       "B",
       "Surface preparation requires patching and repair of cracks or holes, and all wet insulation should be removed and replaced with like materials before coating.",
       f"{K501_CITE} - Page 1"),
    q("K501-005",
       "A contractor power-washes a roof at 1,500 psi before applying 501 Elasto-Brite. What does the data sheet specify for roof surface washing?",
       [("A", "1,500 psi is the maximum allowed to protect modified membranes"),
        ("B", "Wash roof surfaces with a minimum of 2000 psi while taking precautions to avoid roof system damage"),
        ("C", "Power washing is optional when TSP substitute is used on metal only"),
        ("D", "Only brush cleaning is permitted; pressure washing voids the coating warranty")],
       "B",
       "Surfaces should be power washed with TSP substitute and water, and roof surfaces should be washed with a minimum of 2000 psi with precautions to avoid damage to the roof system.",
       f"{K501_CITE} - Page 1"),
    q("K501-006",
       "The coating crew arrives at 6:00 a.m. when the roof thermometer reads 38°F and is forecast to reach 55°F by mid-morning. Should 501 Elasto-Brite application begin?",
       [("A", "Yes; any temperature above freezing is acceptable at dawn"),
        ("B", "No; recommended application temperature is 40°F to 120°F and coating should be applied when 40°F and rising"),
        ("C", "Yes; acrylic coatings may be applied down to 32°F if the second coat follows within 4 hours"),
        ("D", "No; acrylic application requires a minimum of 50°F per Karnak")],
       "B",
       "Recommended application temperature is 40°F to 120°F. Application should occur when temperatures are 40°F and rising but not over 120°F.",
       f"{K501_CITE} - Page 1"),
    q("K501-007",
       "Rain is forecast to begin 18 hours after the crew plans to finish the first coat of 501 Elasto-Brite. What does Karnak caution regarding weather?",
       [("A", "Rain within 12 hours is acceptable if the first coat is brush-applied"),
        ("B", "Do not apply when rain is expected during or within 24 hours after application"),
        ("C", "Only the second coat requires a 48-hour dry window before rain"),
        ("D", "Rain restrictions apply only to spray application, not roller work")],
       "B",
       "501 Elasto-Brite should not be applied when rain is expected during or within 24 hours after application. With rain at 18 hours, coating should not proceed.",
       f"{K501_CITE} - Page 1"),
    q("K501-008",
       "A crew applies the first direct-to-substrate coat of 501 Elasto-Brite at 3:00 p.m. and wants to apply the second coat at 8:00 p.m. the same evening. What dry time does the data sheet require between coats?",
       [("A", "2 to 4 hours minimum regardless of humidity"),
        ("B", "Allow the first coat to dry 8 to 12 hours before application of the second coat"),
        ("C", "Second coat may follow immediately if applied perpendicular to the first"),
        ("D", "24 hours minimum between all acrylic coats on every substrate")],
       "B",
       "501 Elasto-Brite requires allowing the first coat to dry 8 to 12 hours before application of the second coat.",
       f"{K501_CITE} - Page 1"),
    q("K501-009",
       "On a 95°F summer day, a foreman plans one heavy flood coat of 501 Elasto-Brite to speed production. What does Karnak recommend for high-temperature application?",
       [("A", "Single heavy coats are preferred above 90°F to maximize dry mil thickness"),
        ("B", "For applications above 90°F, Karnak recommends application in multiple thin coats to prevent trapped moisture problems"),
        ("C", "Above 90°F, only spray application is permitted; rollers trap heat"),
        ("D", "High temperatures require thinning the coating 10% with water")],
       "B",
       "For applications in higher temperatures above 90°F, Karnak recommends application in multiple thin coats to prevent trapped moisture problems.",
       f"{K501_CITE} - Page 1"),
    q("K501-010",
       "An estimator calculates material for a two-coat direct-to-substrate 501 Elasto-Brite application over 10,000 square feet. What total coverage rate does the data sheet specify?",
       [("A", "1.5 gallons per 100 sq. ft. total for both coats combined"),
        ("B", "3 gallons per 100 sq. ft. total (1.5 gallons per 100 sq. ft. per coat) to achieve 20 to 24 dry mils"),
        ("C", "1 gallon per 100 sq. ft. per coat for acrylic direct application"),
        ("D", "5 gallons per 100 sq. ft. when applied without a Karnak base coat")],
       "B",
       "Direct-to-substrate two-coat application is at 1.5 gallons per 100 sq. ft. per coat for a total of 3 gallons per 100 sq. ft., achieving 20 to 24 dry mils.",
       f"{K501_CITE} - Page 1"),
    q("K501-011",
       "A specifier wants one coat of 501 Elasto-Brite over Karnak 406 Tru-Grip base coat. What coverage rate and wet mil thickness does Karnak specify?",
       [("A", "1 gallon per 100 sq. ft. at 12 wet mils"),
        ("B", "1.5 gallons per 100 sq. ft. at 24 wet mils in a single coat over the applicable 400-series base coat"),
        ("C", "2 gallons per 100 sq. ft. with no mil thickness guidance"),
        ("D", "3 gallons per 100 sq. ft. because base coats count as the first finish coat")],
       "B",
       "Over applicable 400-series base coats, apply 501 Elasto-Brite in a single coat at 1.5 gallons per 100 sq. ft. (24 wet mils).",
       f"{K501_CITE} - Page 1"),
    q("K501-012",
       "A roller crew finishes the first coat of 501 Elasto-Brite running parallel to the base coat direction. What does Karnak specify for roller and brush application orientation?",
       [("A", "All coats must run parallel to the roof slope for drainage"),
        ("B", "Apply with a 3/4\" to 1-1/4\" nap roller or soft roof brush perpendicular to the first coat or base coat"),
        ("C", "Roller direction is unrestricted when using a 1-1/4\" nap roller"),
        ("D", "Only spray application requires cross-direction coverage")],
       "B",
       "Roller and brush application should use a 3/4\" to 1-1/4\" nap roller or soft roof brush perpendicular to the first coat or base coat for proper protection.",
       f"{K501_CITE} - Page 1"),
    q("K501-013",
       "A spray applicator sets up for 501 Elasto-Brite field coating. What overspray pattern does the data sheet require?",
       [("A", "25% overlap with a single-pass wet-on-wet technique"),
        ("B", "50% overspray pattern"),
        ("C", "No overlap; each pass must dry before the next pass"),
        ("D", "75% overlap only when applying over metal substrates")],
       "B",
       "Spray application should be done with a 50% overspray pattern using a heavy-duty professional airless spray pump.",
       f"{K501_CITE} - Page 1"),
    q("K501-014",
       "Standing water remains in a low corner of a retail roof 36 hours after the last rainfall ended. The owner wants 501 Elasto-Brite applied next week. What does Karnak and the cited NRCA drainage criteria indicate?",
       [("A", "Standing water under 48 hours is acceptable if the coating is silicone-based"),
        ("B", "Cold-process coatings should only be installed on decks with positive drainage; NRCA criteria require no standing water 48 hours after rain stops"),
        ("C", "Ponding areas require only double coverage rate, not slope correction"),
        ("D", "Positive drainage is required only on vertical wall surfaces, not horizontal roofs")],
       "B",
       "Cold-process systems and coatings should only be installed on decks with positive drainage. NRCA criteria judge proper slope as no evidence of standing water 48 hours after rain stops.",
       f"{K501_CITE} - Page 1"),
    q("K501-015",
       "A building owner asks why Karnak recommends 501 Elasto-Brite over a Karnak 400-series base coat rather than direct application. What does the data sheet state about recommended use?",
       [("A", "Direct application is always prohibited on every substrate"),
        ("B", "Recommended use is for application over one of Karnak's 400-series substrate-specific base coats"),
        ("C", "400-series base coats are decorative only and do not affect adhesion"),
        ("D", "Base coats are required only on vertical concrete block surfaces")],
       "B",
       "Recommended use is for application over one of Karnak's 400-series substrate-specific base coats, though direct two-coat application is also specified at higher total coverage.",
       f"{K501_CITE} - Page 1"),
    q("K501-016",
       "A crew applies 501 Elasto-Brite over a wet 406 Tru-Grip base coat that has not fully dried. What preparation requirement applies?",
       [("A", "Wet base coats improve acrylic flow and may be coated immediately"),
        ("B", "501 Elasto-Brite or subsequent base coats should be dry prior to application of 501 Elasto-Brite"),
        ("C", "Only the second finish coat requires the base coat to be dry"),
        ("D", "Base coat dryness matters only when temperatures exceed 100°F")],
       "B",
       "501 Elasto-Brite or subsequent base coats should be dry prior to application of 501 Elasto-Brite.",
       f"{K501_CITE} - Page 1"),
    q("K501-017",
       "Fresh masonry parapet walls will be coated with 501 Elasto-Brite on a vertical above-grade application. The walls were poured 15 days ago. What curing period does Karnak require?",
       [("A", "Masonry may be coated immediately if power washed at 2000 psi"),
        ("B", "Allow fresh masonry to cure a minimum of 30 days before application"),
        ("C", "Masonry requires 90 days cure, identical to new BUR roofs"),
        ("D", "Vertical masonry is not an approved substrate for 501 Elasto-Brite")],
       "B",
       "Allow fresh masonry to cure a minimum of 30 days before application. 501 Elasto-Brite is approved on above-grade vertical surfaces including concrete and concrete block.",
       f"{K501_CITE} - Page 1"),
    q("K501-018",
       "An HVAC contractor asks whether rooftop air intakes need protection during 501 Elasto-Brite application. What does Karnak caution?",
       [("A", "Air intakes require protection only during spray application of silicone products"),
        ("B", "Cover air intakes during application and while drying"),
        ("C", "Air intakes may remain open if the coating is water-based acrylic"),
        ("D", "Intake protection is the building owner's responsibility, not the roofer's")],
       "B",
       "Karnak cautions to cover air intakes during application and while drying. This applies to exterior acrylic coating work.",
       f"{K501_CITE} - Page 1"),
    q("K501-019",
       "A warehouse stores 501 Elasto-Brite pails in an unheated outdoor trailer during winter. What storage caution does the data sheet provide?",
       [("A", "Freezing has no effect on acrylic emulsion coatings"),
        ("B", "Protect from freezing; store in a heated room and keep the container covered when not in use"),
        ("C", "Coatings may freeze once but must be stirred for 30 minutes before use"),
        ("D", "Outdoor storage is preferred to maintain application viscosity")],
       "B",
       "Karnak cautions to protect from freezing, store in a heated room, and keep the container covered when not in use.",
       f"{K501_CITE} - Page 1"),
    q("K501-020",
       "A sales rep pitches white 501 Elasto-Brite for a cool-roof rebate program. What initial solar reflectance does the data sheet list for white?",
       [("A", "0.77 initial solar reflectance"),
        ("B", "0.86 initial solar reflectance with 0.77 after 3-year aging"),
        ("C", "0.63 initial solar reflectance matching aluminum coatings"),
        ("D", "Solar reflectance is not published for acrylic elastomeric coatings")],
       "B",
       "White 501 Elasto-Brite has 0.86 initial solar reflectance and 0.77 after 3-year aging, with initial thermal emittance of 0.91.",
       f"{K501_CITE} - Page 1"),
    q("K501-021",
       "A foreman begins 501 Elasto-Brite work without a formal owner sign-off on deck conditions, assuming the existing membrane is sound. What does Karnak state about commencement of work?",
       [("A", "Commencement requires written owner approval on every project"),
        ("B", "Commencement of work by the contractor implies his approval of the deck surface"),
        ("C", "Deck approval must be certified by a third-party inspector before coating"),
        ("D", "Commencement implies approval only when a Karnak representative is on site")],
       "B",
       "Commencement of work by the contractor implies his approval of the deck surface.",
       f"{K501_CITE} - Page 1"),
    q("K501-022",
       "A specifier needs confirmation that 501 Elasto-Brite meets an ASTM acrylic coating specification. Which standard does the data sheet cite?",
       [("A", "ASTM D 6694 for silicone roof coatings"),
        ("B", "ASTM D6083 Type I"),
        ("C", "ASTM D2824 Type III for fibered aluminum"),
        ("D", "ASTM D 2370 for tensile testing only, not product classification")],
       "B",
       "501 Elasto-Brite meets ASTM D6083 Type I.",
       f"{K501_CITE} - Page 1"),
    q("K501-023",
       "At 77°F and 50% relative humidity, how long does Karnak list for cure time of 501 Elasto-Brite?",
       [("A", "2 hours at 95°F and 90% RH"),
        ("B", "24 to 48 hours at 77°F and 50% relative humidity"),
        ("C", "7 to 10 days between coats with 30-day final cure"),
        ("D", "8 to 12 hours, identical to the intercoat dry time")],
       "B",
       "Cure time is listed as 24 to 48 hours at 77°F and 50% relative humidity. Intercoat dry time between first and second coats is 8 to 12 hours.",
       f"{K501_CITE} - Page 1"),
    q("K501-024",
       "A painter asks whether 501 Elasto-Brite may be thinned for easier roller application on a hot day. What does Karnak specify?",
       [("A", "Thin up to 5% water when ambient temperature exceeds 90°F"),
        ("B", "Do not thin"),
        ("C", "Thin only with Karnak 799 Wash-N-Prep for spray work"),
        ("D", "Thinning is permitted for vertical applications only")],
       "B",
       "Karnak cautions: Do not thin. This applies to 501 Elasto-Brite application.",
       f"{K501_CITE} - Page 1"),
    q("K501-025",
       "An owner wants Patina Green on a 200-square-foot accent parapet. The data sheet lists specialty colors. What minimum order quantity applies to non-standard colors?",
       [("A", "50 gallons minimum for any specialty color"),
        ("B", "Specialty colors are available in minimum order quantities of 350 gallons"),
        ("C", "Only White and Portland Gray are manufactured; no other colors exist"),
        ("D", "Specialty colors require a silicone topcoat and cannot be acrylic")],
       "B",
       "White and Portland Gray are standard colors. Specialty colors including Patina Green are available in minimum order quantities of 350 gallons.",
       f"{K501_CITE} - Page 1"),
]

K670 = [
    q("K670HS-001",
       "A restoration contractor plans 670HS Karna-Sil Ultra over newly sprayed polyurethane foam completed yesterday. Is this within the manufacturer's stated uses?",
       [("A", "No; SPF must weather 90 days before any silicone may be applied"),
        ("B", "Yes; newly sprayed polyurethane foam is among the listed approved uses"),
        ("C", "SPF requires 180 Karna-Sil Ultra Epoxy Primer on all foam projects"),
        ("D", "SPF may only receive acrylic coatings, not silicone")],
       "B",
       "670HS Karna-Sil Ultra is designed for newly sprayed polyurethane foam, previously silicone coated roofs, bare galvanized metal, concrete, and multiple membrane types.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-002",
       "A foreman plans 670HS over a smooth built-up asphalt (BUR) roof installed 60 days ago. What aging requirement does Karnak specify for new BUR?",
       [("A", "New BUR surfaces must be allowed to age a minimum of 90 to 180 days"),
        ("B", "New BUR may be coated after 30 days identical to modified bitumen"),
        ("C", "Smooth BUR requires no aging when 406 Tru-Grip is applied first"),
        ("D", "BUR is not listed as an approved substrate for 670HS")],
       "A",
       "New BUR surfaces must be allowed to age a minimum of 90 to 180 days before 670HS application.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-003",
       "A crew will coat painted metal decking with 670HS Karna-Sil Ultra. What primer requirement does the data sheet specify for painted metal?",
       [("A", "No primer is required on any metal surface"),
        ("B", "Painted metal requires 180 Karna-Sil Ultra Epoxy Primer"),
        ("C", "Painted metal requires 406 Tru-Grip Base Coat only"),
        ("D", "Painted metal must be abrasive blasted to bare galvanized before silicone")],
       "B",
       "Bare galvanized metal does not require primer, but painted metal requires 180 Karna-Sil Ultra Epoxy Primer.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-004",
       "An estimator prices 670HS over granule modified bitumen without any base coat or primer. What does Karnak require for smooth and granule modified bitumen membranes?",
       [("A", "Modified bitumen may receive direct silicone without primer after 30 days"),
        ("B", "Requires 406 Tru-Grip Base Coat, 405 Bond-N-Shield Base Coat, or 180 Karna-Sil Ultra Epoxy Primer"),
        ("C", "Only 502MS Karna-Flex may be used as a tie-in, not a field primer"),
        ("D", "Modified bitumen is not approved for 670HS under any preparation")],
       "B",
       "Smooth and granule modified bitumen membranes require 406 Tru-Grip Base Coat, 405 Bond-N-Shield Base Coat, or 180 Karna-Sil Ultra Epoxy Primer.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-005",
       "A concrete parking structure roof will receive 670HS Karna-Sil Ultra. Does Karnak require a primer on concrete?",
       [("A", "Concrete requires 180 epoxy primer on all horizontal applications"),
        ("B", "Concrete roofs are listed with no primer required"),
        ("C", "Concrete requires 507 SPC Primer/Wash identical to EPDM prep"),
        ("D", "Concrete is not an approved substrate for silicone coatings")],
       "B",
       "Concrete roofs are listed as an approved use with no primer required for 670HS Karna-Sil Ultra.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-006",
       "During EPDM surface preparation for 670HS, a crew uses only TSP substitute and water for power washing. What cleaner does Karnak specify for EPDM preparation?",
       [("A", "799 Wash-N-Prep Roof Cleaner or 507 SPC Primer/Wash for EPDM only"),
        ("B", "Any household detergent at 1000 psi is sufficient for EPDM"),
        ("C", "EPDM requires abrasive grinding, not chemical washing"),
        ("D", "507 SPC is prohibited on EPDM; use 799 only on metal")],
       "A",
       "Power wash with 799 Wash-N-Prep Roof Cleaner or 507 SPC Primer/Wash (EPDM Only) and water at minimum 2000 psi.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-007",
       "A silicone crew applies the first coat of 670HS at 10:00 a.m. and wants to apply a second coat at 11:30 a.m. on a cool, humid morning (50°F, 20% RH). What recoat guidance does Karnak provide?",
       [("A", "Recoat may occur immediately after a 30-minute flash-off period"),
        ("B", "Allow the previous coat to cure 2 to 8 hours dependent upon temperature and humidity before subsequent coats"),
        ("C", "Second coats require 24 to 48 hours minimum on all silicone systems"),
        ("D", "670HS is single-coat only; recoat is never permitted")],
       "B",
       "If additional coats are applied, allow the previous coat to cure 2 to 8 hours dependent upon temperature and humidity. At 50°F and 20% RH, cure may be slower.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-008",
       "A foreman plans to recoat a 670HS field area 30 hours after the first coat was applied. What timing limit does Karnak specify for subsequent coats?",
       [("A", "Subsequent coats should be applied within 24 hours of the previous application to ensure uniform adhesion"),
        ("B", "Recoat may occur anytime within 7 days without adhesion risk"),
        ("C", "Silicone recoat windows are unlimited once the first coat is tack-free"),
        ("D", "Recoat must wait 30 days for full cure before any second coat")],
       "A",
       "Subsequent coats should be applied within 24 hours of the previous application to ensure uniform adhesion.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-009",
       "After spray applying 670HS, the inspector notes pinholes in the cured film. What application quality requirement does the data sheet state?",
       [("A", "Pinholes are acceptable if coverage rate meets 1.5 gallons per 100 sq. ft."),
        ("B", "Applied coating film should be even and free of pinholes"),
        ("C", "Pinholes self-heal during the 30-day final cure period"),
        ("D", "Pinholes are only a concern on vertical applications")],
       "B",
       "670HS should be applied so the coating film is even and free of pinholes.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-010",
       "A project spec calls for ceramic granule embedment in the final 670HS coat for aesthetics and toughness. What sequence does Karnak specify?",
       [("A", "Broadcast granules into the primer before any silicone is applied"),
        ("B", "Apply ceramic roofing granules immediately into the final coat after application, back-roll into the coating, allow to cure, then blow off or sweep loose granules"),
        ("C", "Granules must be mixed into the pail before spraying the first coat"),
        ("D", "Granule embedment is prohibited on horizontal silicone roofs")],
       "B",
       "To improve aesthetics, impact resistance, and toughness, ceramic roofing granules should be applied immediately into the final coat after application, back-rolled into the coating, cured, then loose granules blown off or swept.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-011",
       "A spray operator connects 670HS to hoses previously used for acrylic coating application. What hose caution does Karnak specify?",
       [("A", "Acrylic and silicone hoses may be interchanged if flushed with water"),
        ("B", "Do not use hoses that have been used to spray acrylic coatings"),
        ("C", "Hose contamination matters only below 40°F application temperature"),
        ("D", "Acrylic hoses are preferred because they reduce silicone viscosity")],
       "B",
       "Do not use hoses that have been used to spray acrylic coatings with 670HS Karna-Sil Ultra.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-012",
       "A spray crew sets up for 670HS field application. What minimum working pressure at the gun tip does Karnak require?",
       [("A", "3000 psi minimum at the gun tip"),
        ("B", "Minimum of 5500 psi working pressure at the gun tip"),
        ("C", "1500 psi is sufficient for high-solids silicone"),
        ("D", "Pressure is determined solely by the equipment manufacturer with no Karnak minimum")],
       "B",
       "Spray application requires a high-pressure airless spray unit with minimum of 5500 psi working pressure at the gun tip, plus 3 gallon per minute pump output.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-013",
       "An applicator selects a 1/2-inch ID hose for 670HS spray work. What hose specification does the data sheet list?",
       [("A", "1/2-inch ID hoses are preferred for low VOC silicone"),
        ("B", "Hoses should be jacketed for prevention of moisture contamination and have 3/4-inch ID"),
        ("C", "Any hose ID is acceptable if working pressure exceeds 3000 psi"),
        ("D", "Hose ID is irrelevant; only tip orifice size matters")],
       "B",
       "Hoses should be jacketed for prevention of moisture contamination, have 3/4-inch ID, and tip size should be minimum 0.041 orifice.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-014",
       "A spray technician needs to select a spray tip for 670HS. What minimum orifice size does Karnak specify?",
       [("A", "0.021 orifice for fine mist coverage"),
        ("B", "Minimum tip orifice size of 0.041"),
        ("C", "0.055 orifice required only on vertical applications"),
        ("D", "Tip size is not specified; pump GPM alone determines atomization")],
       "B",
       "Tip size should be a minimum size 0.041 orifice for spray application of 670HS.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-015",
       "A pump rated at 2 gallons per minute is available for 670HS spray application. Does it meet Karnak equipment requirements?",
       [("A", "Yes; 2 GPM exceeds minimum requirements for silicone"),
        ("B", "No; the pump must have a 3 gallon per minute output"),
        ("C", "GPM requirements apply only to acrylic coatings, not silicone"),
        ("D", "2 GPM is acceptable when hose ID is increased to 1 inch")],
       "B",
       "The pump must have a 3 gallon per minute output for 670HS spray application.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-016",
       "An estimator calculates standard field coverage for 670HS on a 15,000 sq. ft. smooth BUR restoration. What default coverage rate does Karnak list for most applications?",
       [("A", "1 gallon per 100 sq. ft. at 12 wet mils"),
        ("B", "1.5 gallons per 100 sq. ft. (24 wet mils) in a single coat for most applications"),
        ("C", "3 gallons per 100 sq. ft. required on every substrate"),
        ("D", "0.75 gallons per 100 sq. ft. when applied over primer")],
       "B",
       "Apply in a single coat at 1.5 gallons per 100 sq. ft. (24 wet mils) for most applications.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-017",
       "A foreman wants to apply up to 3 gallons per 100 sq. ft. of 670HS in one application on a horizontal approved substrate. Is this permitted?",
       [("A", "No; 670HS is always limited to 1.5 gallons per 100 sq. ft."),
        ("B", "Yes; may be applied up to 3 gallons per 100 sq. ft. on approved horizontal substrates in one application where applicable"),
        ("C", "3 gallons per 100 sq. ft. is only permitted on vertical walls"),
        ("D", "Maximum single-pass coverage is 2 gallons per 100 sq. ft. on any substrate")],
       "B",
       "670HS may be applied up to 3 gallons per 100 sq. ft. on approved horizontal substrates in one application, where applicable.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-018",
       "At 95°F and 90% relative humidity, how long does Karnak list for 670HS cure time?",
       [("A", "24 to 48 hours identical to acrylic coatings"),
        ("B", "2 hours at 95°F and 90% RH"),
        ("C", "8 hours at 95°F regardless of humidity"),
        ("D", "30 days final cure before foot traffic")],
       "B",
       "Cure time is listed as 2 hours at 95°F and 90% RH, compared to 8 hours at 50°F and 20% RH.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-019",
       "A crew arrives when the roof temperature is 45°F for 670HS application. What application temperature range does Karnak specify?",
       [("A", "40°F to 120°F identical to acrylic elastomerics"),
        ("B", "50°F to 120°F; application should not begin at 45°F"),
        ("C", "32°F minimum for moisture-curing silicone"),
        ("D", "45°F is acceptable if the coating is heated to 70°F in the pail")],
       "B",
       "Recommended application temperature is 50°F to 120°F. Apply at temperatures 50°F to 120°F.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-020",
       "Rain is expected 20 hours after 670HS application will finish. Should the crew proceed?",
       [("A", "Yes; silicone cures in 2 hours and rain at 20 hours is acceptable"),
        ("B", "No; do not apply if rain is expected within 24 hours after application"),
        ("C", "Rain within 12 hours is the only restriction for silicone coatings"),
        ("D", "Rain restrictions apply only when granules are embedded")],
       "B",
       "Do not apply if rain is expected within 24 hours after application.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-021",
       "A crew mixes half a 5-gallon pail of 670HS and plans to store the remainder for next week. What does Karnak state about mixing?",
       [("A", "Partial pails may be resealed and used within 30 days"),
        ("B", "Once product is mixed, the entire container should be used"),
        ("C", "Mixing is optional for brush application only"),
        ("D", "Mix only with a drill paddle under 500 RPM for 30 seconds")],
       "B",
       "Mix coating prior to application with a 3-inch diameter mixer for 5-gallon pails. Once product is mixed, the entire container should be used.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-022",
       "Standing water is observed 24 hours after rainfall on a roof scheduled for 670HS. What drainage requirement does Karnak cite?",
       [("A", "Ponding is acceptable if silicone is applied at 3 gallons per 100 sq. ft."),
        ("B", "All surfaces must have positive drainage; NRCA criteria require no standing water 48 hours after rain stops"),
        ("C", "Positive drainage is required only on newly sprayed foam"),
        ("D", "Drainage requirements are waived on previously silicone coated roofs")],
       "B",
       "All surfaces must have positive drainage. NRCA criteria judge proper slope as no evidence of standing water 48 hours after rain stops.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-023",
       "A new SBS granule modified membrane was installed 25 days ago. The owner wants 670HS applied next week. Has the minimum weathering period been met?",
       [("A", "No; SBS granular modified membranes must weather a minimum of 30 days"),
        ("B", "Yes; 25 days exceeds the 21-day industry standard"),
        ("C", "SBS membranes require 90 to 180 days before any silicone"),
        ("D", "Granule modified membranes may be coated immediately with primer")],
       "A",
       "SBS and APP granular modified membranes and smooth surface APP membranes must be allowed to weather a minimum of 30 days.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-024",
       "A spray crew is setting up 670HS on a windy day and asks about static spark risk. What safety caution does Karnak provide for spraying?",
       [("A", "Static sparks are not a concern with low VOC silicone"),
        ("B", "Equipment should be grounded to avoid accidental ignition due to static sparks when spraying"),
        ("C", "Grounding is required only when VOC exceeds 450 g/L"),
        ("D", "Spray application is prohibited when wind exceeds 5 mph")],
       "B",
       "If spraying, equipment should be grounded to avoid accidental ignition due to static sparks.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-025",
       "A foreman needs to patch open seams before 670HS field coating. Which Karnak repair products does the data sheet list for seams, flashings, splits, and cracks?",
       [("A", "19 Ultra Rubberized Flashing Cement only"),
        ("B", "502MS Karna-Flex, 505MS Karna-Flex WB, 671 Karna-Seal, or appropriate sealants or caulking materials"),
        ("C", "406 Tru-Grip only; mastics are not approved for seam repair"),
        ("D", "Any polyurethane caulk from a hardware store")],
       "B",
       "Patch and repair seams, flashings, damaged areas, splits, and cracks with 502MS Karna-Flex, 505MS Karna-Flex WB, 671 Karna-Seal, or appropriate sealants or caulking materials.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-026",
       "A specifier asks which ASTM standard the 670HS data sheet references for silicone roof coatings.",
       [("A", "ASTM D6083 Type I for acrylic elastomerics"),
        ("B", "ASTM D 6694"),
        ("C", "ASTM D2824 Type III for fibered aluminum"),
        ("D", "ASTM D 2370 for elongation testing only")],
       "B",
       "670HS Karna-Sil Ultra is associated with ASTM D 6694 in the physical properties section.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-027",
       "A cold-storage facility owner asks about the cured film service temperature range for 670HS. What does Karnak list?",
       [("A", "-15°F to 180°F matching acrylic elastomerics"),
        ("B", "-75°F to 380°F for the cured silicone film"),
        ("C", "15°F to 180°F identical to aluminum coatings"),
        ("D", "Service temperature is not published for silicone coatings")],
       "B",
       "Service temperature for the cured film is -75°F to 380°F.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-028",
       "A vertical parapet wall will receive 670HS and the foreman worries one coat may not build enough film thickness. What does Karnak note about vertical application?",
       [("A", "Vertical application is prohibited for 670HS"),
        ("B", "Vertical application may require multiple coats to achieve desired film thickness"),
        ("C", "Vertical surfaces always require double the horizontal coverage rate"),
        ("D", "Vertical work must use brush only; spray is not permitted")],
       "B",
       "670HS may be used on vertical as well as horizontal applications. Vertical application may require multiple coats to achieve desired film thickness.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-029",
       "A sales rep pitches white 670HS for an energy rebate. What initial solar reflectance does the data sheet list?",
       [("A", "0.86 initial, matching 501 Elasto-Brite acrylic"),
        ("B", "0.87 initial solar reflectance (white only) with 0.70 after 3-year aging"),
        ("C", "0.63 initial, matching fibered aluminum coatings"),
        ("D", "Solar reflectance is not listed for high-solids silicone")],
       "B",
       "White 670HS has 0.87 initial solar reflectance and 0.70 after 3-year aging, with initial thermal emittance of 0.89.",
       f"{K670_CITE} - Page 1"),
    q("K670HS-030",
       "A warehouse stores 670HS drums in a shed that may reach 105°F in summer. What storage temperature limit does Karnak specify?",
       [("A", "No maximum storage temperature is listed"),
        ("B", "Do not store above 100°F; keep containers properly sealed indoors in a cool well-ventilated area"),
        ("C", "Silicone may be stored up to 120°F matching application temperature"),
        ("D", "Drums must be stored below 50°F to prevent cure")],
       "B",
       "Keep containers properly sealed when stored indoors in a cool well-ventilated area. Do not store above 100°F.",
       f"{K670_CITE} - Page 1"),
]

K97 = [
    q("K97-001",
       "A building owner asks why 97 Fibered Aluminum Roof Coating is specified over a modified bitumen roof instead of a generic gray asphalt emulsion. What primary protective mechanism does Karnak describe?",
       [("A", "The aluminum flakes absorb UV radiation to heat the membrane for winter flexibility"),
        ("B", "Aluminum flakes leaf to the surface providing a reflective metallic shield; over 50% of the sun's rays are reflected, protecting asphaltic oils from being cooked out"),
        ("C", "Fibered aluminum penetrates into the membrane to replace lost asphalt oils"),
        ("D", "The coating forms a rubberized membrane that eliminates all thermal movement")],
       "B",
       "Aluminum flakes leaf to the surface providing a reflective metallic shield. Over 50% of the sun's rays are reflected, preventing asphaltic oils from being cooked out of the roof substrate.",
       f"{K97_CITE} - Page 1"),
    q("K97-002",
       "A facility manager wants to reduce summer cooling costs on a modified bitumen warehouse roof. How does Karnak describe the indoor temperature benefit of 97 Fibered Aluminum?",
       [("A", "The coating insulates the deck to retain winter heat only"),
        ("B", "During hot summer months, the coating helps reduce indoor building temperatures by reflecting the sun's rays and reducing roof surface temperatures"),
        ("C", "Indoor temperature reduction requires a white acrylic topcoat over the aluminum"),
        ("D", "Reflectivity benefits apply only to metal corrugated decks, not modified bitumen")],
       "B",
       "During hot summer months, 97 Fibered Aluminum Roof Coating helps reduce indoor building temperatures and improve inside living and working conditions by reflecting the sun's rays and reducing roof surface temperatures.",
       f"{K97_CITE} - Page 1"),
    q("K97-003",
       "A specifier needs confirmation of fire performance for 97 Fibered Aluminum over modified bitumen. What rating does the data sheet cite?",
       [("A", "UL Class B rating over all substrates"),
        ("B", "UL Class A rated over specified modified bitumen systems, UL Listing #Rl2l99 (N)"),
        ("C", "FM 1-90 wind uplift only; no fire rating is published"),
        ("D", "Fire rating applies only when applied over metal corrugated decks")],
       "B",
       "One coat extends modified bitumen membrane life by limiting fire spread as indicated by the UL Class A rating over specified modified bitumen systems, UL Listing #Rl2l99 (N).",
       f"{K97_CITE} - Page 1"),
    q("K97-004",
       "A crew plans to apply 97 Fibered Aluminum over a new steep asphalt roof installed 60 days ago. What weathering period does Karnak require?",
       [("A", "Steep asphalt roofs must weather a minimum of 90 days before coating"),
        ("B", "New asphalt roofs may be coated after 30 days"),
        ("C", "Steep asphalt may be coated immediately if swept clean"),
        ("D", "Steep asphalt requires 180 days identical to smooth BUR silicone prep")],
       "A",
       "New asphalt roof surfaces should weather a minimum of 90 days before being coated with 97 Fibered Aluminum Roof Coating.",
       f"{K97_CITE} - Page 1"),
    q("K97-005",
       "A contractor applied Karnak asphalt emulsion roof coating five days ago and wants to apply 97 Fibered Aluminum today. Is this within Karnak's stated uses?",
       [("A", "No; emulsion coatings require 90 days before any aluminum may be applied"),
        ("B", "Yes; 97 may be used on any Karnak emulsion roof coating that has been allowed to cure for 3 to 5 days"),
        ("C", "Emulsion must cure 60 days minimum before aluminum application"),
        ("D", "Aluminum may only be applied over silicone, not asphalt emulsion")],
       "B",
       "97 Fibered Aluminum is ideal for modified bitumen, metal corrugated decks, steep asphalt roofs aged 90 days, or any Karnak emulsion roof coating cured 3 to 5 days.",
       f"{K97_CITE} - Page 1"),
    q("K97-006",
       "A roof surface shows severe alligatoring on aged asphalt. Before 97 Fibered Aluminum application, what primer does Karnak recommend?",
       [("A", "Apply 97 directly; alligatoring improves aluminum leafing"),
        ("B", "Prime with Karnak 100 Non-Fibered Emulsion Primer or 220 Fibered Emulsion Roof Coating prior to aluminum coating"),
        ("C", "Use 180 Karna-Sil Ultra Epoxy Primer on all asphalt surfaces"),
        ("D", "Alligatored surfaces require tear-off; no primer can restore them")],
       "B",
       "Badly weathered or alligatored asphalt surfaces should be primed with Karnak 100 Non-Fibered Emulsion Primer or 220 Fibered Emulsion Roof Coating prior to 97 application.",
       f"{K97_CITE} - Page 1"),
    q("K97-007",
       "After applying 100 Non-Fibered Emulsion Primer on an alligatored asphalt roof, how long must the primer cure before 97 Fibered Aluminum application?",
       [("A", "24 hours minimum in warm weather"),
        ("B", "Allow emulsion primer or coating to cure a minimum of 3 to 5 days before aluminum application"),
        ("C", "60 days minimum identical to flashing cement dry time"),
        ("D", "Primer may be coated immediately if aluminum is brush-applied")],
       "B",
       "Allow emulsion primer or coating to cure a minimum of 3 to 5 days before application of aluminum roof coating.",
       f"{K97_CITE} - Page 1"),
    q("K97-008",
       "During 97 Fibered Aluminum application, a roller crew repeatedly re-rolls the same area to improve uniformity. What does Karnak warn about application technique?",
       [("A", "Multiple re-rolling improves aluminum leafing and reflectivity"),
        ("B", "Care should be taken not to overwork the coating during application because this could have a damaging effect on the leafing of the aluminum"),
        ("C", "Overworking is only a concern on vertical surfaces"),
        ("D", "Overworking is recommended to embed aluminum flakes deeper into the asphalt")],
       "B",
       "Care should be taken not to overwork the coating during application. Overworking could have a damaging effect on the leafing of the aluminum.",
       f"{K97_CITE} - Page 1"),
    q("K97-009",
       "A foreman asks the correct application method for 97 Fibered Aluminum to preserve the metallic finish. What technique does Karnak specify?",
       [("A", "Apply in a crisscross pattern with multiple thin passes"),
        ("B", "Pour the correct amount to cover a given area and work it in one direction"),
        ("C", "Spray only; brushing destroys aluminum leafing permanently"),
        ("D", "Flood coat and squeegee back in two directions")],
       "B",
       "Pour the correct amount of aluminum roof coating to cover a given area and work it in one direction. Spread uniformly without overworking.",
       f"{K97_CITE} - Page 1"),
    q("K97-010",
       "Before opening a pail of 97 Fibered Aluminum, what mixing requirement does Karnak specify?",
       [("A", "Do not mix; aluminum flakes must remain settled at the bottom"),
        ("B", "Mechanically mix the aluminum roof coating thoroughly before using"),
        ("C", "Stir by hand for 30 seconds only; mechanical mixing damages fibers"),
        ("D", "Thin 10% before mixing to distribute aluminum flakes")],
       "B",
       "Be sure to mechanically mix the aluminum roof coating thoroughly before using.",
       f"{K97_CITE} - Page 1"),
    q("K97-011",
       "A crew patches blisters with Karnak 19 Ultra Rubberized Flashing Cement and reinforcement, then plans 97 Fibered Aluminum in 30 days. What discoloration risk does Karnak warn about?",
       [("A", "No discoloration risk exists when 19 is used as patch material"),
        ("B", "Discoloration will occur in areas where 19 Ultra Rubberized Flashing Cement is not allowed to dry a minimum of 60 days"),
        ("C", "Discoloration occurs only when aluminum is applied over silicone coatings"),
        ("D", "30 days dry time for 19 is sufficient before aluminum application")],
       "B",
       "Discoloration will occur in areas where 19 Ultra Rubberized Flashing Cement is not allowed to dry a minimum of 60 days.",
       f"{K97_CITE} - Page 1"),
    q("K97-012",
       "After 19 Ultra Rubberized Flashing Cement patches have dried 60 days, what application temperature guidance does Karnak provide for 97?",
       [("A", "Apply at any temperature above 32°F"),
        ("B", "After 60 days, recommended application temperatures are 50°F and rising"),
        ("C", "Apply only when temperature is between 40°F and 90°F"),
        ("D", "Temperature requirements are waived after the 60-day flashing cement cure")],
       "B",
       "After 60 days, recommended application temperatures are 50°F and rising. General application temperature range is 50°F to 120°F.",
       f"{K97_CITE} - Page 1"),
    q("K97-013",
       "An estimator calculates material for 97 Fibered Aluminum on 8,000 square feet. What coverage rate range does Karnak specify?",
       [("A", "0.5 to 1 gallon per 100 sq. ft."),
        ("B", "1 to 1.5 gallons per 100 sq. ft. (16 to 24 wet mils)"),
        ("C", "3 gallons per 100 sq. ft. identical to acrylic two-coat systems"),
        ("D", "2 gallons per 100 sq. ft. minimum on all substrates")],
       "B",
       "Apply at 1 to 1.5 gallons per 100 sq. ft. (16 to 24 wet mils).",
       f"{K97_CITE} - Page 1"),
    q("K97-014",
       "A painter wants to thin 97 Fibered Aluminum for easier spray application on a hot day. What does Karnak specify?",
       [("A", "Thin up to 5% with mineral spirits when temperature exceeds 90°F"),
        ("B", "DO NOT THIN"),
        ("C", "Thin only with Karnak 100 Non-Fibered Emulsion Primer"),
        ("D", "Thinning is permitted for metal corrugated decks only")],
       "B",
       "Coverage instructions state DO NOT THIN. Caution also states do not thin.",
       f"{K97_CITE} - Page 1"),
    q("K97-015",
       "Rain is expected 30 hours after 97 Fibered Aluminum will be applied. What moisture restriction does Karnak specify?",
       [("A", "Coating must not come in contact with any type of moisture within 24 to 48 hours after application"),
        ("B", "Rain within 12 hours is acceptable if the coating is fibered"),
        ("C", "Moisture contact is permitted after 6 hours of dry time"),
        ("D", "Moisture restrictions apply only to emulsion primers, not aluminum topcoats")],
       "A",
       "Coating must not come in contact with any type of moisture within 24 to 48 hours after application.",
       f"{K97_CITE} - Page 1"),
    q("K97-016",
       "A torch-applied APP modified bitumen roof was installed today. When should Karnak recommend applying 97 Fibered Aluminum?",
       [("A", "Wait 90 days minimum on all torch-applied membranes"),
        ("B", "Karnak recommends coating torch-applied modified bitumen membranes as soon as possible after membrane installation"),
        ("C", "Torch-applied membranes may never receive aluminum coatings"),
        ("D", "Wait 60 days to match flashing cement dry requirements")],
       "B",
       "Karnak recommends coating torch-applied modified bitumen membranes as soon as possible after membrane installation to reduce UV, heat, and moisture effects that enhance exudation on APP.",
       f"{K97_CITE} - Page 1"),
    q("K97-017",
       "A foreman asks why prompt aluminum coating on new APP modified bitumen matters. What problem does Karnak describe on APP membranes?",
       [("A", "APP membranes lose all reflectivity within 24 hours without aluminum"),
        ("B", "UV rays, heat, and moisture especially on APP enhance exudation that can cause discoloring and delamination of any surface coating"),
        ("C", "APP requires aluminum only for fire rating; UV damage is not a concern"),
        ("D", "APP exudation is cosmetic only and does not affect coating adhesion")],
       "B",
       "Aluminum coating reduces combined effects of ultraviolet rays, heat, and moisture which especially on APP modified bitumen enhance exudation that can cause discoloring and delamination of any surface coating.",
       f"{K97_CITE} - Page 1"),
    q("K97-018",
       "A crew prepares a modified bitumen roof for 97 Fibered Aluminum by power washing at 2500 psi. What surface preparation does Karnak specify?",
       [("A", "Power wash at minimum 2000 psi before all aluminum applications"),
        ("B", "Prepare all surfaces by sweeping clean of dust, dirt, loose rust, oil, and loose particles"),
        ("C", "Chemical etching with TSP is required on all modified bitumen"),
        ("D", "Surface prep requires only rinsing; sweeping is optional")],
       "B",
       "Prepare all surfaces by sweeping clean of dust, dirt, loose rust, oil, and loose particles. Recommended application temperature is 50°F to 120°F.",
       f"{K97_CITE} - Page 1"),
    q("K97-019",
       "A blister repair on a modified bitumen roof requires patching before 97 application. What repair sequence does Karnak specify?",
       [("A", "Cut out blisters and apply 97 directly into the cavity"),
        ("B", "Spread Karnak 19 Ultra Rubberized Flashing Cement over the damaged area, embed Karnak Asphalt Cotton, Fiberglass, Poly-Mat or Resat-Mat reinforcement, then apply another coat of 19 over the entire patch"),
        ("C", "Apply 100 Non-Fibered Emulsion Primer only; mastic is not used for blister repair"),
        ("D", "Inject polyurethane foam into blisters and coat the same day")],
       "B",
       "Repair cracks and blisters by spreading 19 Ultra Rubberized Flashing Cement, embedding reinforcement (Asphalt Cotton, Fiberglass, Poly-Mat or Resat-Mat), then applying another coat of 19 over the entire patch.",
       f"{K97_CITE} - Page 1"),
    q("K97-020",
       "Standing water remains on a low-slope roof 40 hours after rain stopped. The owner wants 97 Fibered Aluminum applied. What drainage requirement does Karnak cite?",
       [("A", "Ponding is acceptable for solvent-based aluminum coatings"),
        ("B", "Cold-process coatings should only be installed on decks with positive drainage; no standing water 48 hours after rain stops per NRCA criteria"),
        ("C", "Positive drainage is required only for acrylic emulsion systems"),
        ("D", "Drainage requirements apply only when aluminum is applied over emulsion primer")],
       "B",
       "Cold-process systems and coatings should only be installed on decks with positive drainage. NRCA criteria require no evidence of standing water 48 hours after rain stops.",
       f"{K97_CITE} - Page 1"),
    q("K97-021",
       "A specifier asks which ASTM standard applies to 97 Fibered Aluminum Roof Coating classification.",
       [("A", "ASTM D6083 Type I"),
        ("B", "ASTM D2824 Type III"),
        ("C", "ASTM D 6694"),
        ("D", "ASTM D 2370 only")],
       "B",
       "97 Fibered Aluminum Roof Coating is listed with ASTM D2824 Type III, along with TT-C-498C, ASTM D3805, and ASTM D962 Type II.",
       f"{K97_CITE} - Page 1"),
    q("K97-022",
       "A sales rep cites reflectivity for an energy audit. What initial solar reflectance does Karnak publish for 97 Fibered Aluminum?",
       [("A", "0.87 initial matching high-solids silicone"),
        ("B", "0.63 initial solar reflectance with 0.55 after 3-year aging"),
        ("C", "0.86 initial matching white acrylic elastomerics"),
        ("D", "Reflectance is not published for aluminum coatings")],
       "B",
       "Solar reflectance is 0.63 initial and 0.55 after 3-year aging, with initial thermal emittance of 0.46.",
       f"{K97_CITE} - Page 1"),
    q("K97-023",
       "A metal corrugated roof deck will receive maintenance coating. Is 97 Fibered Aluminum within Karnak's stated uses?",
       [("A", "No; metal decks require silicone or acrylic only"),
        ("B", "Yes; metal corrugated roof decks are listed ideal uses"),
        ("C", "Metal corrugated decks require 180 epoxy primer before aluminum"),
        ("D", "Only steep asphalt roofs may receive fibered aluminum")],
       "B",
       "97 Fibered Aluminum is ideal for modified bitumen membranes, metal corrugated roof decks, steep asphalt roofs aged 90 days, and Karnak emulsion coatings cured 3 to 5 days.",
       f"{K97_CITE} - Page 1"),
    q("K97-024",
       "A safety officer asks about fire and fume hazards during 97 Fibered Aluminum application near a rooftop kitchen exhaust. What cautions does Karnak list?",
       [("A", "No fire hazard; water-based products only near exhausts"),
        ("B", "Do not use near open flame; avoid breathing solvent fumes and prolonged skin contact"),
        ("C", "Open flame is permitted after the coating skins over"),
        ("D", "Solvent fumes are harmless; only interior use is prohibited")],
       "B",
       "Caution: Do not use near open flame. Avoid breathing solvent fumes and prolonged contact with skin. Exterior use only.",
       f"{K97_CITE} - Page 1"),
    q("K97-025",
       "A rooftop air handler intake is 10 feet from the coating work area. What building protection does Karnak require during 97 application?",
       [("A", "Air intakes require protection only during interior painting"),
        ("B", "Cover air intakes during application and while drying"),
        ("C", "Air intakes may remain open for solvent-based coatings if wind is calm"),
        ("D", "Intake protection is the mechanical contractor's responsibility")],
       "B",
       "Cover air intakes during application and while drying. Store in a heated room and keep container covered when not in use.",
       f"{K97_CITE} - Page 1"),
]

def redistribute_answers(questions):
    letters = ["A", "B", "C", "D"]
    out = []
    for i, q in enumerate(questions):
        target = letters[i % 4]
        correct_id = q["answer"]
        correct_text = next(o["text"] for o in q["options"] if o["id"] == correct_id)
        wrong_texts = [o["text"] for o in q["options"] if o["id"] != correct_id]
        new_options = []
        wrong_i = 0
        for letter in letters:
            if letter == target:
                new_options.append({"id": letter, "text": correct_text})
            else:
                new_options.append({"id": letter, "text": wrong_texts[wrong_i]})
                wrong_i += 1
        out.append({**q, "options": new_options, "answer": target})
    return out

BANKS = [
    ("karnak-501-elasto-brite-question-bank-2026.js",
     "Karnak 501 Elasto-Brite",
     "KARNAK_501_ELASTO_BRITE_QUESTION_BANK_2026",
     "501-elasto-brite-pds.pdf",
     25,
     K501),
    ("karnak-670hs-karna-sil-ultra-question-bank-2026.js",
     "Karnak 670HS Karna-Sil Ultra",
     "KARNAK_670HS_KARNA_SIL_ULTRA_QUESTION_BANK_2026",
     "670hs-karna-sil-ultra-pds.pdf",
     30,
     K670),
    ("karnak-97-fibered-aluminum-question-bank-2026.js",
     "Karnak 97 Fibered Aluminum Roof Coating",
     "KARNAK_97_FIBERED_ALUMINUM_QUESTION_BANK_2026",
     "97-fibered-aluminum-pds.pdf",
     25,
     K97),
]

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

def format_question(q, indent="    "):
    lines = [f"{indent}{{"]
    lines.append(f"{indent}  id: {js_str(q['id'])},")
    lines.append(f"{indent}  type: {js_str(q['type'])},")
    lines.append(f"{indent}  question: {js_str(q['question'])},")
    lines.append(f"{indent}  options: [")
    for opt in q["options"]:
        lines.append(f"{indent}    {{ id: {js_str(opt['id'])}, text: {js_str(opt['text'])} }},")
    lines.append(f"{indent}  ],")
    lines.append(f"{indent}  answer: {js_str(q['answer'])},")
    lines.append(f"{indent}  explanation: {js_str(q['explanation'])},")
    lines.append(f"{indent}  cite: {js_str(q['cite'])},")
    lines.append(f"{indent}  exhibitImage: \"\",")
    lines.append(f"{indent}  imageRef: \"\"")
    lines.append(f"{indent}}},")
    return "\n".join(lines)

def write_bank(filename, book, const_prefix, source_pdf, target_count, questions):
    assert len(questions) == target_count
    raw = f"{const_prefix}_RAW"
    out = []
    out.append(f"// {book} - Question Bank")
    out.append("// BANK-ONLY (exam generation only, NOT listed in /api/books)")
    out.append("//")
    out.append(f"// Source PDF: {source_pdf}")
    out.append(f"// Authoring target: {target_count} technical data sheet questions grounded in source text.")
    out.append("")
    out.append(SANITIZE_HEADER.strip())
    out.append("")
    out.append(f"const {raw} = {{")
    out.append(f"  book: {js_str(book)},")
    out.append("  questions: [")
    for q in questions:
        out.append(format_question(q))
    out.append("  ]")
    out.append("};")
    out.append("")
    out.append(f"const {const_prefix} = {{")
    out.append(f"  ...{raw},")
    out.append(f"  questions: {raw}.questions.map(sanitizeQuestion)")
    out.append("};")
    out.append("")
    out.append(f"module.exports = {const_prefix};")
    out.append("")
    path = os.path.join(EXAM_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    return path, len(questions)

if __name__ == "__main__":
    for fn, book, prefix, pdf, count, qs in BANKS:
        balanced = redistribute_answers(qs)
        path, n = write_bank(fn, book, prefix, pdf, count, balanced)
        print(f"  {fn}: {n} questions -> {path}")
