name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # We aren't building a framework app here, so skip build detection.
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"   # your index.html is here
          api_location: "api"        # your Azure Functions (chat, diag)
          output_location: ""        # no build output folder
          skip_app_build: true       # important for plain static sites
